# Generated by Django 3.1 on 2020-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='None', max_length=30)),
                ('Birthday', models.DateField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
